logging:
  level:
    org.springframework: 'WARN'
    org.apache.catalina: 'WARN'
    org.apache.tomcat: 'ERROR'
    org.hibernate: 'WARN'

server:
  port: 8080

---
spring:
  profiles: dev

app:
  baseURL: http://localhost:8080
  jdbcURL: jdbc:mysql://localhost/generic
  jdbcUser: generic
  jdbcPass: generic

---
spring:
  profiles: test

app:
  baseURL: http://localhost:8080
  jdbcURL: empty
  jdbcUser: empty
  jdbcPass: empty

---
spring:
  profiles: prod

server:
  port: 8100
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto

app:
  baseURL: http://localhost:8080
  jdbcURL: jdbc:mysql://localhost/generic
  jdbcUser: generic
  jdbcPass: generic


